### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.models'

### ISSUE THREAD

**Issue by rs1990** [OTL/rostensorflow#2]
Hi,

I’m new to Tensorflow and am trying to test this package. but i keep getting this error. 

  File "image_recognition.py", line 9, in <module>
    from tensorflow.models.image.imagenet import classify_image
ModuleNotFoundError: No module named 'tensorflow.models'

Id appreciate any help. 
thanks

RS

**Comment by OTL** [comment]
Hi, thank you for feedback!

What is the version of ternsorflow?
This is created for v0.9, i guess that it is too old.

If you can install v0.9, how about trying it first?

If you can fix the library path for newest tensorflow, PR is welcome!

**Comment by rs1990** [comment]
im using version 1.2.1.

I tried fixing that but i get this issue now : 

````
raghavendra_sriram@mav:~/indigo_ws/src/rostensorflow$ python image_recognition.py image:=/cv_camera/image_raw
Traceback (most recent call last):
  File "image_recognition.py", line 54, in <module>
    tensor = RosTensorFlow()
  File "image_recognition.py", line 19, in __init__
    classify_image.maybe_download_and_extract()
  File "/home/raghavendra_sriram/indigo_ws/src/models/tutorials/image/imagenet/classify_image.py", line 172, in maybe_download_and_extract
    dest_directory = FLAGS.model_dir
AttributeError: 'NoneType' object has no attribute 'model_dir'
````

**Comment by rs1990** [comment]
Are there any other necessary requirements to run this package ?

**Comment by OTL** [comment]
Hi, newest classify_image.py seems that it needs some modification. So I copied it in my repo, and
modified to use from my program.

And I push the new version, which supports kinetic and latest tensorflow for you!!!
Please update, and try it again!

**Comment by rs1990** [comment]
Hello,
 Thanks a lot. Sorry i couldnt get back to you earlier. I managed to get the previous version working with tensorflow 0.9. Il try this with tensorflow 1.0 and get back. 


Cheers.

**Comment by OTL** [comment]
don't mind, and you don't need to be harry.

2017/08/09 8:07 "Raghavendra Sriram" <notifications@github.com>:

Hello,
Thanks a lot. Sorry i couldnt get back to you earlier. I managed to get the
previous version working with tensorflow 0.9. Il try this with tensorflow
1.0 and get back.

Cheers.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/OTL/rostensorflow/issues/2#issuecomment-321106337>, or mute
the thread
